---
title: "Crosstalk"
subtitle: "Shiny-like without Shiny?"
author: "Matt Dray | Dept for Education | EARL 2018"
output:
  xaringan::moon_reader:
    css: ["default", "rladies-fonts"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

class: center, middle

# TL;DR

Insert TL;DR.

---

class: center, middle

# The problem

Visualise and explore school locations to help make a policy decision.

---
class: inverse, center, middle

# Solution 0

GIS software

---

# Solution 0

.pull-left[
## +

* Powerful
* Output easy to share
]
--
.pull-right[
## &ndash;

* Limited licenses for ArcGIS
* Admin rights needed for QGIS
* Click... click... click...
* No interactivity
* Ping-pong feature requests
* Limited knowledge in the department
* Already a backlog
]

---

class: inverse, center, middle

# Solution 1

`leaflet` interactive map

---

# Solution 1

.pull-left[
## +

* Interactivity (pan, zoom, layers, etc)
* Relatively simple code
* Powerful functions
* Share as HTML file
* Run in-browser
]
--
.pull-right[
## &ndash;

* Need separate documentation
* Need separate tabular data file
* Rendered in browser
]

---
class: inverse, center, middle

# Solution 2

`leaflet` interactive map
<p>in a `flexdashboard`

---

# Solution 2

.pull-left[
## +

* Documentation alongside map
* More user friendly
]
--
.pull-right[
## &ndash;

* Can't display tabular data alongside
]

---
class: inverse, center, middle

# Solution 3

`leaflet` interactive map
<p>in a `flexdashboard`
<p>with a `datatable`

---

# Solution 3
.pull-left[
## +

* Documentation alongside map
* Tabular data alongside map
* Users can download the data
]
--
.pull-right[
## &ndash;

* Map and tabular data aren't linked
]

---
class: inverse, center, middle

# Solution 4

`leaflet` interactive map
<p>in a `flexdashboard`
<p>with a `datatable`
<p>and linked with `crosstalk`

---

# Solution 4

.pull-left[
## +

* Documentation alongside map
* Tabular data alongside map
* Users can download the data
* Can add filter elements
* Data link between `htmlwidgets
]
--
.pull-right[
## &ndash;
insert something
]

---
class: center, middle

# TL;DR

Insert TL;DR.

---
class: inverse, center, middle

# Contact

Matt Dray

[matthew.dray@education.gov.uk](mailto:matthew.dray@education.gov.uk)

[rostrum.blog](https://rostrum.blog) | [twitter.com/mattdray](https://www.twitter.com/mattdray) | [github.com/matt-dray](https://www.github.com/matt-dray)